// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchArvanIPs():Promise<Array<string>>;

export function GetConfig():Promise<Record<string, any>>;

export function StartScan(arg1:main.ScanRequest):Promise<void>;

export function StopScan():Promise<void>;
