// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchArvanIPs() {
  return window['go']['main']['App']['FetchArvanIPs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
